max_width = 80
tab_spaces = 2

# All of these are currently unstable options; turn them on once they are
# available

#normalize_comments = true
#wrap_comments = true
# Unstable features, turn on once stable
#unstable_features = true
#merge_imports = true
#struct_lit_single_line = true
#indent_style = 'Visual'
#comment_width = 80
#binop_separator = 'Back'
#remove_blank_lines_at_start_or_end_of_block = true
#match_block_trailing_comma = true
#use_try_shorthand = true
#use_field_init_shorthand = true
