unstable_features = true
max_width = 80
comment_width = 80
wrap_comments = true
tab_spaces = 4
indent_style = 'Visual'
struct_lit_single_line = true
binop_separator = 'Back'
merge_imports = true
match_block_trailing_comma = true
normalize_comments = true
use_field_init_shorthand = true
use_try_shorthand = true
remove_blank_lines_at_start_or_end_of_block = true
