language: rust
rust:
  - beta
  - nightly
  - stable
os:
  - linux
  - osx

before_script:
  - (cargo install rustfmt || true)

script:
  - |
    export PATH=$PATH:~/.cargo/bin &&
    cargo fmt -- --write-mode=diff &&
    cargo build &&
    cargo test
