language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt --all -- --write-mode=checkstyle
  - cargo build
  - cargo test
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
